apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: job1
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: hello-world
        name: job1
        resources: {}
      restartPolicy: Never
status: {}
